# Node
FROM node:20-alpine

# criar pasta
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# instalar dependencias
RUN npm install

# copia todo o resto do projeto
COPY . .

#Expõe a porta
EXPOSE 5000

#roda aplicação
CMD ["node", "index.js"]